"use strict";
/**
 * THE FREE-PERIOD BOOKING QUOTA.
 *
 * /api/book had no limit of any kind: a bare proxy through to Railway and on
 * to SportyBet and Bet9ja. Slip building is free client-side compute, so the
 * only thing worth metering is the booking call - Railway runs on a $5 plan
 * with a $5 usage cap, and Bet9ja has block-paged the datacentre once already.
 *
 * TWO RULES SHAPE EVERYTHING HERE.
 *
 * 1. The device is the subject, not the IP. MTN and Airtel NAT very large
 *    numbers of subscribers behind single addresses, so a per-IP daily cap
 *    would lock out a whole cell tower while a script on a VPS sailed through.
 *    The IP ceiling exists, but it is set for scripts, not people.
 *
 * 2. It fails OPEN. A quota that cannot be read must never cost a reader their
 *    slip - the same rule the shared-slip page follows for its record line.
 *    Losing count is cheaper than losing the booking.
 *
 * The day is Lagos, not UTC. "Ten a day" has to mean the day the reader is
 * living in, and Nigeria is UTC+1 all year with no daylight saving.
 */
const test = require("node:test");
const assert = require("node:assert");
const Q = require("../lib/quota.js");

/* ------------------------------------------------------------- the day */

test("the day rolls over at midnight in Lagos, not in London", () => {
  /* 23:30 UTC is already tomorrow for the reader this site is built for. */
  assert.equal(Q.dayOf(Date.parse("2026-09-07T23:30:00Z")), "2026-09-08");
  assert.equal(Q.dayOf(Date.parse("2026-09-07T22:30:00Z")), "2026-09-07");
});

test("the day is stable across a call, whatever the server's timezone", () => {
  const t = Date.parse("2026-09-07T12:00:00Z");
  assert.equal(Q.dayOf(t), Q.dayOf(t), "same instant, same day string");
  assert.match(Q.dayOf(t), /^\d{4}-\d{2}-\d{2}$/);
});

/* --------------------------------------------------------- the device id */

test("a well-formed device id is accepted", () => {
  assert.equal(Q.deviceIdOf({ headers: { "x-sw-device": "a1B2c3D4e5F6" } }), "a1B2c3D4e5F6");
});

test("anything that is not an opaque token is refused", () => {
  /* The id is generated by the browser and never trusted: it reaches a
     database key, so its shape is checked rather than its contents. */
  const bad = ["", "  ", "short", "has spaces in it", "semi;colon", "../../etc/passwd",
               "x".repeat(65), "drop table"];
  for (const v of bad) {
    assert.equal(Q.deviceIdOf({ headers: { "x-sw-device": v } }), null, JSON.stringify(v));
  }
  assert.equal(Q.deviceIdOf({ headers: {} }), null, "absent is not an error, just unknown");
  assert.equal(Q.deviceIdOf({}), null, "a request with no headers at all must not throw");
});

/* ------------------------------------------------------------- the client */

test("the IP is hashed before it is stored, never kept raw", () => {
  /* It is only ever a bucket key. Keeping the address itself would put
     personal data in a table that exists to count bookings. */
  const a = Q.clientKeyOf({ headers: { "x-forwarded-for": "105.112.4.9" } }, "pepper");
  assert.match(a, /^[0-9a-f]{16}$/, "a short hex digest, got " + a);
  assert.ok(!a.includes("105"), "the address must not survive into the key");
});

test("the same address hashes to the same bucket, a different one does not", () => {
  const a = Q.clientKeyOf({ headers: { "x-forwarded-for": "105.112.4.9" } }, "pepper");
  const b = Q.clientKeyOf({ headers: { "x-forwarded-for": "105.112.4.9" } }, "pepper");
  const c = Q.clientKeyOf({ headers: { "x-forwarded-for": "41.58.1.2" } }, "pepper");
  assert.equal(a, b);
  assert.notEqual(a, c);
});

test("a different pepper gives a different bucket for the same address", () => {
  /* So a leaked table cannot be walked back to addresses with a rainbow table
     of the v4 space, which is small enough to enumerate. */
  const a = Q.clientKeyOf({ headers: { "x-forwarded-for": "105.112.4.9" } }, "pepper-one");
  const b = Q.clientKeyOf({ headers: { "x-forwarded-for": "105.112.4.9" } }, "pepper-two");
  assert.notEqual(a, b);
});

test("the first address in a forwarded chain is the client", () => {
  const k = Q.clientKeyOf({ headers: { "x-forwarded-for": "105.112.4.9, 172.16.0.1, 10.0.0.1" } }, "p");
  const direct = Q.clientKeyOf({ headers: { "x-forwarded-for": "105.112.4.9" } }, "p");
  assert.equal(k, direct, "proxies appended to the chain must not change the bucket");
});

test("no address at all is a null key rather than a shared bucket", () => {
  /* Bucketing every address-less request together would let one of them
     exhaust the ceiling for all of them. */
  assert.equal(Q.clientKeyOf({ headers: {} }, "p"), null);
  assert.equal(Q.clientKeyOf({}, "p"), null);
});

/* --------------------------------------------------------- the decision */

test("under the cap is allowed, and says how much is left", () => {
  const d = Q.decide({ used: 3, limit: 10 });
  assert.equal(d.allow, true);
  assert.equal(d.remaining, 7);
});

test("the tenth code of the day is allowed and the eleventh is not", () => {
  /* The boundary is the whole feature: "ten a day" must mean ten, not nine. */
  assert.equal(Q.decide({ used: 9, limit: 10 }).allow, true, "the tenth is still free");
  assert.equal(Q.decide({ used: 9, limit: 10 }).remaining, 1);
  assert.equal(Q.decide({ used: 10, limit: 10 }).allow, false, "the eleventh is not");
  assert.equal(Q.decide({ used: 10, limit: 10 }).remaining, 0);
});

test("remaining never reads as a negative number", () => {
  /* Two requests can race past the same count, so used may exceed the limit.
     A reader is told zero, never "-3 left". */
  assert.equal(Q.decide({ used: 13, limit: 10 }).remaining, 0);
  assert.equal(Q.decide({ used: 13, limit: 10 }).allow, false);
});

test("an unknown count fails open", () => {
  /* The counter was unreachable. Losing count is cheaper than losing the
     booking, so the reader books and we simply do not know the number. */
  for (const used of [null, undefined, NaN, "lots"]) {
    const d = Q.decide({ used, limit: 10 });
    assert.equal(d.allow, true, "unknown usage must not block; got " + JSON.stringify(used));
    assert.equal(d.counted, false, "and must say it did not count");
  }
});

test("a counted decision says so, so the caller can tell the two apart", () => {
  assert.equal(Q.decide({ used: 3, limit: 10 }).counted, true);
});

test("a missing limit means no limit rather than a limit of zero", () => {
  /* An unset env var must not lock the whole site out of booking. */
  for (const limit of [null, undefined, 0, NaN, "ten"]) {
    assert.equal(Q.decide({ used: 999, limit }).allow, true,
      "limit " + JSON.stringify(limit) + " must read as switched off");
  }
});
