"use strict";
/* GENERATED by scripts/mkslipedit.js from public/index.html - do not edit.
   Re-run that script after changing these edits in the page. */
function trimToOdds(rows,target){
  var priced=[],unpriced=[];
  (rows||[]).forEach(function(r){ (r&&+r.odds>1.01?priced:unpriced).push(r); });
  priced.sort(function(a,b){
    var pa=a.p==null?-1:a.p, pb=b.p==null?-1:b.p;
    return (pb-pa)||(a.odds-b.odds);
  });
  var keep=[],prod=1;
  for(var i=0;i<priced.length&&prod<target;i++){
    var next=prod*priced[i].odds;
    if(next>target&&keep.length&&Math.log(next/target)>Math.log(target/prod)) break;
    keep.push(priced[i]); prod=next;
  }
  return {keep:keep,cut:priced.slice(keep.length).concat(unpriced),odds:prod,
          short:prod<target&&keep.length===priced.length};
}
var CHANGE_FROM={
  draw:{label:"Draws",codes:["X"]},
  home:{label:"Home wins",codes:["1"]},
  away:{label:"Away wins",codes:["2"]},
  win:{label:"Wins",codes:["1","2"]},
  dc:{label:"Double chance",codes:["1X","X2"]},
  o15:{label:"Over 1.5",codes:["OVER_1.5"]},
  o25:{label:"Over 2.5",codes:["OVER_2.5"]},
  o35:{label:"Over 3.5",codes:["OVER_3.5"]},
  u15:{label:"Under 1.5",codes:["UNDER_1.5"]},
  u25:{label:"Under 2.5",codes:["UNDER_2.5"]},
  u35:{label:"Under 3.5",codes:["UNDER_3.5"]},
  gg:{label:"Both teams to score",codes:["GG"]},
  ng:{label:"Not both to score",codes:["NG"]}
};
var CHANGE_TO={
  dc:{label:"Win or draw (same side)",map:{"1":"1X","2":"X2"}},
  "12":{label:"Any team to win",code:"12"},
  o15:{label:"Over 1.5",code:"OVER_1.5"},
  o25:{label:"Over 2.5",code:"OVER_2.5"},
  u25:{label:"Under 2.5",code:"UNDER_2.5"},
  u35:{label:"Under 3.5",code:"UNDER_3.5"},
  gg:{label:"Both teams to score",code:"GG"},
  ng:{label:"Not both to score",code:"NG"}
};
function changeAllPlan(legs,from,to){
  var F=CHANGE_FROM[from], T=CHANGE_TO[to], changed=[];
  if(!F||!T) return {legs:(legs||[]).slice(),changed:changed};
  var out=(legs||[]).map(function(l){
    if(!l||F.codes.indexOf(l.prediction)<0) return l;
    var nc=T.map?T.map[l.prediction]:T.code;
    if(!nc||nc===l.prediction) return l;
    var n={}; for(var k in l) n[k]=l[k];
    n.prediction=nc; n.odds=null;
    changed.push({leg:l,from:l.prediction,to:nc});
    return n;
  });
  return {legs:out,changed:changed};
}
function changeOptions(legs){
  var out=[];
  Object.keys(CHANGE_FROM).forEach(function(f){
    var n=(legs||[]).filter(function(l){ return l&&CHANGE_FROM[f].codes.indexOf(l.prediction)>=0; }).length;
    if(!n) return;
    var tos=Object.keys(CHANGE_TO).filter(function(t){ return changeAllPlan(legs,f,t).changed.length>0; });
    if(tos.length) out.push({from:f,n:n,to:tos});
  });
  return out;
}
module.exports = { trimToOdds, CHANGE_FROM, CHANGE_TO, changeAllPlan, changeOptions };
