"use strict";
/* GENERATED by scripts/mkteammatch.js from public/index.html - do not edit.
   Re-run that script after changing the matcher in the page. */
var TEAM_ALIASES = {
  "athletico": "paranaense",
  "inter miami cf": "inter miami",
  "b. dortmund": "borussia dortmund",
  "b. monchengladbach": "borussia monchengladbach",
  "vfb stuttgart": "stuttgart",
  "sv werder bremen": "werder bremen",
  "rasenballsport leipzig": "leipzig",
  "eintracht frankfurt": "frankfurt",
  "bayern": "bayern munich",
  "bayer": "bayer leverkusen",
  "wolfsburg": "vfl wolfsburg",
  "hoffenheim": "tsg hoffenheim",
  "heidenheim": "1. fc heidenheim",
  "st. pauli": "fc st pauli",
  "union berlin": "1. fc union berlin",
  "real madrid cf": "real madrid",
  "atletico madrid": "atletico de madrid",
  "athletic bilbao": "athletic club",
  /* football-data abbreviates this one; "ath" is too short for the prefix rule
     in simTeams to bridge, so the two feeds scored 0.5 and missed each other. */
  "ath bilbao": "athletic club",
  "deportivo alaves": "alaves",
  "celta vigo": "celta de vigo",
  "real sociedad": "sociedad",
  "real betis": "betis",
  "valencia cf": "valencia",
  "villarreal cf": "villarreal",
  "sevilla fc": "sevilla",
  "getafe cf": "getafe",
  "osasuna": "ca osasuna",
  "mallorca": "rcd mallorca",
  "rayo vallecano": "rayo",
  /* Our feed says "Vallecano", SportyBet says "Rayo Vallecano". Without this
     the two scored zero against each other, which is half of how a La Liga
     fixture came to be booked as an Ecuadorian one - see sameSlot below. */
  "vallecano": "rayo",
  "girona fc": "girona",
  "las palmas": "ud las palmas",
  "cadiz cf": "cadiz",
  "almeria": "ud almeria",
  "granada cf": "granada",
  "ac milan": "milan",
  "inter": "internazionale",
  "as roma": "roma",
  "ss lazio": "lazio",
  "ssc napoli": "napoli",
  "juventus fc": "juventus",
  "torino fc": "torino",
  "fiorentina": "acf fiorentina",
  "bologna fc": "bologna",
  "udinese": "udinese calcio",
  "sassuolo": "us sassuolo",
  "empoli fc": "empoli",
  "salernitana": "us salernitana",
  "lecce": "us lecce",
  "cagliari": "cagliari calcio",
  "genoa": "genoa cfc",
  "hellas verona": "verona",
  "frosinone": "frosinone calcio",
  "psv eindhoven": "psv",
  "feyenoord": "feyenoord rotterdam",
  "az alkmaar": "az",
  "twente": "fc twente",
  "utrecht": "fc utrecht",
  "heerenveen": "sc heerenveen",
  "zwolle": "pec zwolle",
  "groningen": "fc groningen",
  "heracles": "heracles almelo",
  /* Our side is aliased to "sbv excelsior" while the odds feed writes
     "Excelsior Rotterdam", and neither name contains the other - so the club
     could not be matched from either direction. Both spellings now land on
     the same canonical name. */
  "excelsior": "sbv excelsior",
  "excelsior rotterdam": "sbv excelsior",
  "volendam": "fc volendam",
  "almere city": "almere city fc",
  "n.e.c.": "nec nijmegen",
  "sparta rotterdam": "sparta",
  /* ------------------------------------------------------------------
     Abbreviations one feed uses and the other does not. Every one of these
     was a fixture that could never be priced, taken from a live matcher log.
     They are exact whole-name keys, so none can fire on a name that merely
     contains the abbreviation. */
  /* QPR COLLAPSES DOWN, NOT UP, AND THE DIRECTION IS THE WHOLE POINT.
     Aliasing "qpr" to the full "queens park rangers" fixed the reported miss
     and bought two far worse matches with it: the full name contains "rangers"
     as a whole word and "queens park" as a whole phrase, so QPR scored 1.80
     against GLASGOW RANGERS and against Queens Park FC - two other clubs, one
     of them in a different country. Caught by diffing every name pair the live
     feeds produce; it would have shown up as a Premiership fixture priced off
     a Championship one.
     Mapping the long name down to the short one has no such reach: "qpr"
     contains nothing and is contained by nothing. Any feed spelling of the
     club lands on it, and neither Rangers nor Queens Park can get near it.
     The lesson generalises - when a club's full name contains another club's
     whole name, alias TOWARD the form that does not. */
  "queens park rangers": "qpr",
  /* TWO CLUBS CALLED AMERICA, IN TWO COUNTRIES. Club America of Mexico City
     normalises to bare "america", which is a whole-word containment inside
     America de Cali's "america cali" - so the two scored 1.80, the figure
     reserved for an exact or containing name, and a Liga MX fixture could be
     priced off a Colombian one. Giving the Mexican club its full name keeps
     the two apart while still matching either feed's spelling of it, since
     both arrive here as "america" before this line runs. */
  "america": "club america",
  "for sittard": "fortuna sittard",
  "inverness c": "inverness caledonian thistle",
  /* "the" is stripped before aliases run, so the feed's "Queen of the South"
     arrives here as "queen of south". */
  "queen of sth": "queen of south",
  "airdrie united": "airdrieonians",
  "volos nps": "volos nfc",
  "rapid bucuresti": "rapid 1923",
  /* FCSB, WITH A CAVEAT WORTH KNOWING. The Bucharest club plays as FCSB in one
     feed and Steaua in the other, and without this it matched nothing at all.
     But CSA Steaua Bucuresti is a DIFFERENT, lower-division club carrying the
     same name, so this alias makes the two collide if they ever appear on one
     card. They are separated by division, not by name, and that is the whole
     of the protection - if the tier filter is ever loosened, revisit this
     line first. */
  "fcsb": "steaua bucharest",
  "rkC waalwijk": "rkC",
  "sc freiburg": "freiburg",
  "vfl bochum": "bochum",
  "vfl wolfsburg": "wolfsburg",
  "fc koln": "koln",
  "ath madrid": "atletico de madrid",
  "cologne": "koln",
  "1 fc nuremberg": "nurnberg",
  "1 nuremberg": "nurnberg",
  "fotbal club fcsb": "steaua bucharest",
  "sheffield wednesday": "sheffield weds",
  "m'gladbach": "monchengladbach",
  "mgladbach": "monchengladbach",
  "eif": "ekenas",
  "hamburger sv": "hamburg",
  "hamburger": "hamburg",
  "fotbal fcsb": "steaua bucharest",
  "m gladbach": "monchengladbach",
  "borussia m gladbach": "monchengladbach",
  "borussia mgladbach": "monchengladbach",
  "borussia monchengladbach": "monchengladbach",
  "borussia mgladbach": "monchengladbach",
  "tsg 1899 hoffenheim": "hoffenheim",
  "sv darmstadt 98": "darmstadt",
  "fc heidenheim": "heidenheim",
  "fc union berlin": "union berlin",
  "1. fc koln": "koln",
  "1. fc heidenheim": "heidenheim",
  "1. fc union berlin": "union berlin",
  "fc st. pauli": "st. pauli",
  "fc augsburg": "augsburg",
  "vfb stuttgart": "stuttgart",
  "eintracht frankfurt": "frankfurt",
  "bayer 04 leverkusen": "leverkusen",
  "borussia dortmund": "dortmund",
  "fc bayern munchen": "bayern munich",
  "rb leipzig": "leipzig",
  /* Finnish clubs are known by their initials on our side and written out in
     full by SportyBet, so the two share no token at all and scored zero. Both
     spellings fold to the long form. */
  "sjk": "seinajoen jk",
  "tps": "turun palloseura",
  "kups": "kuopion palloseura",
  "vps": "vaasan palloseura",
  "hjk": "hjk helsinki",
  "ifk mariehamn": "mariehamn",
  /* The first alias Bet9ja has needed, and the only one so far.
     They list Rosario Central as "Atletico Rosario" - the club is Club
     Atletico Rosario Central and their feed keeps the wrong two words of it.
     Identified rather than guessed: the fixture is against Newell's Old Boys,
     which is the Rosario derby, kicking off the same minute as ours, and the
     Argentine top flight has no club called Atletico Rosario. It costs a
     second fixture as well - they carry "Tigre - Atletico Rosario" a week
     later. */
  "atletico rosario": "rosario central",
  /* Renamed, and the feeds have not agreed on it. */
  "shenzhen xinpengcheng": "shenzhen peng city",
  /* Both were matching, but only on kick-off time with the name scoring
     0.00 - the clock carrying a pairing the names could not. That works
     until two games in the same league start together, and then the
     fixture goes unpriced. Greek ει against ι is one letter, so the
     containment rule misses by a hair; Basaksehir is a different word
     in each feed. Aliased to the same canonical form, not bridged with a
     general rule: "istanbul" alone would also match Kasimpasa Istanbul. */
  "levadeiakos": "levadiakos",
  "buyuksehyr": "basaksehir",
  "istanbul bb": "basaksehir",
};
var MATCH_WINDOW_MS=24*60*60*1000;
function normTeam(s){
  var k=s||"";
  var hit=NT_CACHE[k];
  if(hit!==undefined) return hit;
  var v=normTeamRaw(k);
  if(NT_SIZE<NT_MAX){NT_CACHE[k]=v;NT_SIZE++;}
  return v;
}
function normTeamRaw(s){
  s=(s||"").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g,"");
  s=s.replace(/ø/g,"o").replace(/æ/g,"ae").replace(/å/g,"a").replace(/ß/g,"ss")
     .replace(/đ/g,"d").replace(/ð/g,"d").replace(/ł/g,"l").replace(/ı/g,"i").replace(/þ/g,"th");
  /* Every punctuation mark, not a hand-picked five. "Saint Patrick´s" carries
     U+00B4, an acute accent standing in for an apostrophe, which survived the
     old class and left the token as "patrick´s" - so it matched nothing. The
     transliterations above have already done their work by this point, so
     anything still not a letter, digit or space is a separator. */
  s=s.replace(/[^a-z0-9 ]/g," ");
  /* Transliteration collapse: our data and SportyBet disagree on how they
     romanise Scandinavian vowels - Brondby vs Broendby (ø), Valerenga vs
     Vaalerenga (å). Collapse both spellings to the short form so they match. */
  s=s.replace(/oe/g,"o").replace(/aa/g,"a");
  s=s.replace(/\butd\b/g,"united");
  /* Abbreviated qualifiers. Our feed writes "Dep. Riestra", "Atl. Tucuman",
     "Ind. Rivadavia", "St. Patricks"; SportyBet writes them out in full. The
     token compare below will not bridge a three-letter stub to its full word,
     so bridge it here. Which spelling wins does not matter - both feeds run
     through this same function, so all that matters is that they converge. */
  s=s.replace(/\bdep\b/g,"deportivo").replace(/\batl\b/g,"atletico")
     .replace(/\bind\b/g,"independiente");
  /* "st" is deliberately not expanded. It looked obvious - "St. Patricks"
     against "Saint Patrick's" - but Saint is not the only thing it stands for:
     "St. Gilloise" is Union Saint-Gilloise, which SportyBet lists as "Union
     Gilloise", and expanding ours to "saint gilloise" pushed the two apart.
     Left alone the stub is two characters, dropped by tokset, and the clubs
     match on the name that actually distinguishes them. */
  /* Only expansions an actual miss called for. A speculative "univ" ->
     "universidad" looked harmless and broke Romania: Rapid Bucuresti v Univ.
     Craiova had been matching, and Craiova is Universitatea, not Universidad,
     so the expansion pushed the two spellings apart. An abbreviation means
     different things in different languages - leave the stub alone unless a
     real miss shows it has to go. */
  /* Same club, different language. */
  s=s.replace(/\bvienna\b/g,"wien");
  /* Cross-feed spelling variants seen in the wild (RU/AR leagues). */
  s=s.replace(/\bdynamo\b/g,"dinamo").replace(/\btogliatti\b/g,"tolyatti")
     .replace(/\bjrs\b/g,"juniors").replace(/\bjr\b/g,"juniors");
  s=s.replace(/\bman united\b/g,"manchester united").replace(/\bman city\b/g,"manchester city")
     .replace(/\bpsg\b/g,"paris").replace(/\bparis sg\b/g,"paris").replace(/\bparis saint germain\b/g,"paris")
     .replace(/\bspurs\b/g,"tottenham").replace(/\bwolves\b/g,"wolverhampton")
     .replace(/\bnott m forest\b/g,"nottingham forest").replace(/\bnottm forest\b/g,"nottingham forest")
     .replace(/\bwest brom\b/g,"west bromwich").replace(/\bespanyol\b/g,"espanol")
     .replace(/\bolympiacos\b/g,"olympiakos").replace(/\baustria lustenau\b/g,"lustenau")
     /* Transliteration and abbreviation seen across the two feeds. Krylia and
        Krylya are the same Samara club spelt two ways, and one feed adds the
        city while the other does not - collapsing the spelling lets ordinary
        word containment do the rest. "Rvs" is how the Scottish feed shortens
        Rovers. */
     .replace(/\bkrylya\b/g,"krylia").replace(/\brvs\b/g,"rovers")
     .replace(/\ba lustenau\b/g,"lustenau").replace(/\batromitos athinon\b/g,"atromitos");
  s=s.replace(/^\s*sporting\s*$/,"sp lisbon");
  s=s.replace(/\b(pa|sp|rj|mg|rs|sc|pr|ce|ba|go|pe|df|am|mt|ms|es|pb|rn|al|pi|ma|to|ap|ac|ro|rr|se)\b/g," ");
  s=s.replace(/\b(fc|fk|cf|afc|ac|as|sv|us|ss|ssc|cd|ca|sk|if|bk|clube|club|do|da|de|dos|das|the|ec|se|ad|aa|cr|futebol)\b/g," ");
  s=s.replace(/\s+/g," ").trim();
  /* Apply aliases AFTER cleaning so we match the canonical form */
  if (TEAM_ALIASES[s]) s = TEAM_ALIASES[s];
  /* ...then put the alias through the same transliteration collapse the rest of
     the name already went through. Without this an alias had to be written in
     the collapsed spelling to work at all: "seinajoen jk" never matched the
     feed, because the feed's own "Seinajoen JK" had already become
     "seinajon jk" up above, and "vaasan" had become "vasan". Aliases can now be
     written the way the club is actually spelt. */
  s = s.replace(/oe/g,"o").replace(/aa/g,"a").replace(/\s+/g," ").trim();
  return s;
}
function tokset(s){
  var k=s||"";
  var C=tokset.C||(tokset.C=Object.create(null));
  var hit=C[k];
  if(hit!==undefined) return hit;
  var v=normTeam(k).split(" ").filter(function(w){return w.length>=3;});
  /* On the function, not in a module-level var, and capped like NT_CACHE.
     Two test files lift these functions out of the page by name and run them
     standalone; a cache declared outside would be undefined there, and the
     first thing anyone would do is stub it in the test - which is a second
     place to keep in step. Self-contained, it travels. */
  tokset.n=tokset.n||0;
  if(tokset.n<20000){C[k]=v;tokset.n++;}
  return v;
}
function teamMarkers(s){
  /* Cached alongside tokset above - see that comment for the measurement and
     for why this is safe. This is the more expensive of the two: it runs
     normalize("NFD") and three regexes over the raw name on every call, and
     sameVariant asks for BOTH sides before simTeams scores anything at all.
     The cache hangs off the function rather than sitting in a module-level
     var, and that is deliberate: test/variant.test.js lifts this function out
     of the page by name and evaluates it on its own, so a cache declared
     outside it would be undefined there. Self-contained, it travels. */
  var ck=s||"";
  var C=teamMarkers.C||(teamMarkers.C=Object.create(null));
  var hit=C[ck];
  if(hit!==undefined) return hit;
  var out={}, n=0;
  var raw=" "+String(s==null?"":s).toLowerCase().normalize("NFD")
    .replace(/[̀-ͯ]/g,"").replace(/[^a-z0-9]+/g," ")+" ";
  function add(k){ if(!out[k]){out[k]=1;n++;} }
  /* Anchored to the END of the name. A reserve side is "Sociedad B",
     "Portland Timbers II", "Rosenborg BK 2" - the marker is always a
     suffix. Matching it anywhere would catch the Danish club B 93 and the
     Faroese B36 and B68, whose names simply begin with a B, and then a
     feed writing "B93" against one writing "B 93" would disagree about
     the marker and refuse a perfectly good match. */
  if(/ (ii|2|b) $/.test(raw)) add("reserves");
  /* A HYPHENATED NUMBER IS A RESERVE SIDE WHEREVER IT SITS. The rule above is
     anchored to the end of the name for good reason - see the comment - but
     the Russian feeds write the second team as "Dinamo-2 Makhachkala" and
     "Spartak-2 Moscow", with the city still to come. Measured: our first-team
     "Dinamo Makhachkala" scored 1.00 against "FC Dinamo-2 Makhachkala" with no
     marker found on either side.
     The hyphen is what makes this safe to read anywhere in the name, so it is
     tested against the ORIGINAL string, before punctuation is flattened to
     spaces. B 93 and B36 carry no hyphen and are untouched. */
  if(/-\s?(2|3|ii|iii)\b/i.test(String(s==null?"":s))) add("reserves");
  if(/ iii $/.test(raw)) add("third");
  if(/ (u ?1[5-9]|u ?2[0-3]) /.test(raw)) add("youth");
  /* ZhFK is the Russian women's-club prefix, transliterated. Measured: our
     "Krylya Sovetov" scored 1.80 against "Zhfk Krylya Sovetov Samara" - the
     women's side of the same club, an exact containment with no marker
     anywhere for the guard to catch. Wfc and Zhfc are the same abbreviation
     spelt differently. */
  if(/ (women|feminin|femenino|femenina|frauen|ladies|zhfk|zhfc|wfc) /.test(raw)) add("women");
  if(/ (reserves?|academy|youth|jugend|primavera|junioren) /.test(raw)) add("youth");
  /* Dutch reserve sides are named "Jong Ajax", with no numeral at all. */
  if(/ jong /.test(raw)) add("reserves");
  out.__n=n;
  /* Capped for the same reason NT_CACHE is: club names, not user input, but a
     runaway feed should not grow this without bound. */
  teamMarkers.n=teamMarkers.n||0;
  if(teamMarkers.n<20000){C[ck]=out;teamMarkers.n++;}
  return out;
}
function sameVariant(a,b){
  var A=teamMarkers(a), B=teamMarkers(b);
  if(A.__n===B.__n){
    for(var k in A){ if(k!=="__n" && !B[k]) return false; }
    return true;
  }
  /* A FIRST TEAM WHOSE NAME ENDS IN A MARKER. Willem II is an Eredivisie club,
     not anybody's reserve side, and the marker rule is anchored to the end of
     the name - so "Willem II" reads as a reserve team while "Willem II
     Tilburg" does not, the two disagree, and simTeams returns 0. Measured: the
     fixture could never be matched at all, whatever the feed called it.
     The direction is what tells the two cases apart, and it is exact:
       marked name is a WORD-PREFIX of the unmarked one   -> same club
         "Willem II" inside "Willem II Tilburg" - the II belongs to the name,
         and the extra words are the rest of the club, not a squad.
       unmarked name is a word-prefix of the marked one   -> different
         "Stuttgart" against "Stuttgart II" - the marker is a suffix on a name
         that stands alone without it, which is exactly a reserve side.
     Everything else stays refused, so B 93 and Rosenborg BK 2 are untouched. */
  var marked   = A.__n>B.__n ? a : b;
  var unmarked = A.__n>B.__n ? b : a;
  var nm=normTeam(marked), nu=normTeam(unmarked);
  if(!nm||!nu) return false;
  return nm.length<nu.length && containsWords(nu,nm) && nu.indexOf(nm)===0;
}
function containsWords(outer,inner){
  if(!inner||inner.length>outer.length) return false;
  var i=outer.indexOf(inner);
  while(i>=0){
    var beforeOk = i===0 || outer.charAt(i-1)===" ";
    var end=i+inner.length;
    /* A trailing s still ends the word. Nordic and Spanish names carry it as a
       genitive or a feminine ending, not as a different club: Djurgarden
       against "Djurgardens IF", Aalesund against "Aalesunds FK", Espanol
       against "Union Espanola". Measured over 1.56m live name pairs, those
       three were the only real clubs a strict boundary lost, and allowing the
       one letter brings back none of the coincidences - every one of those
       fails on the character BEFORE the match, not after it. */
    if(end<outer.length && (outer.charAt(end)==="s"||outer.charAt(end)==="a")) end++;
    var afterOk = end===outer.length || outer.charAt(end)===" ";
    if(beforeOk&&afterOk) return true;
    i=outer.indexOf(inner,i+1);
  }
  return false;
}
function simTeams(a,b){
  var na=normTeam(a),nb=normTeam(b);
  if(!na||!nb) return 0;
  /* Asked before similarity, not after: a containing name scores 1.8 and
     would otherwise sail past every check below. */
  if(!sameVariant(a,b)) return 0;
  if(na===nb) return 2.0;  // max score for perfect match
  /* CONTAINMENT, ON WORD BOUNDARIES. A plain indexOf matches inside a word,
     and the names this feed carries are full of the resulting nonsense:
     "Tanta" sits inside "Farul ConsTANTA" and "Sparta" inside "SPARTAk
     Moscow", both scoring 1.8 - the score reserved for an exact or containing
     name. Measured on the live feeds, those two alone were one date check away
     from booking somebody onto the wrong fixture, and a wrong match is the one
     failure nothing downstream can correct.
     Requiring the shorter name to start and end on a word boundary keeps every
     real case - "Otelul" in "Otelul Galati", "Kalamata" in "PAE PS Kalamata" -
     and drops the coincidences. */
  if(containsWords(na,nb)||containsWords(nb,na)) return 1.8;
  var ta=tokset(a),tb=tokset(b),sh=0;
  /* "Urawa Reds" against "Urawa Red Diamonds" turned on nothing more than a
     plural: "reds" and "red" are not equal, and the prefix rule below needs
     four characters on both sides, which "red" does not have. A trailing s is
     not a different club. */
  function same(x,y){
    if(x===y) return true;
    if(x.length>=4&&y.length>=4&&(x.indexOf(y)===0||y.indexOf(x)===0)) return true;
    var sx=x.replace(/s$/,""), sy=y.replace(/s$/,"");
    return sx.length>=3&&sx===sy;
  }
  ta.forEach(function(x){ if(tb.some(function(y){return same(x,y);})) sh++; });
  return sh/Math.max(1,Math.min(ta.length,tb.length));
}
function evStart(m){
  var t=m&&m.startTime;
  if(t==null) return NaN;
  if(typeof t==="number") return t;
  var n=Number(t);
  if(isFinite(n)&&n>1e11) return n;
  return Date.parse(t);
}
function sameSlot(f,m){
  if(!f||!f.kickoff) return true;
  var t=evStart(m); if(!isFinite(t)) return true;
  var k=Date.parse(f.kickoff); if(!isFinite(k)) return true;
  return Math.abs(t-k)<=MATCH_WINDOW_MS;
}
var NT_CACHE=Object.create(null),NT_SIZE=0;const NT_MAX=20000;
module.exports = { normTeam, simTeams, sameSlot, evStart, sameVariant };
