#!/usr/bin/env node
/* Writes lib/slipedit.js: the slip edits the converter uses (trim to odds,
 * change a market everywhere), lifted verbatim out of public/index.html for
 * the Telegram bot - the same reason and the same way as mkteammatch.js.
 *
 *   node scripts/mkslipedit.js
 *
 * test/slipedit.test.js fails the moment the page's copy changes and this has
 * not been re-run.
 */
const fs = require("fs");
const path = require("path");
const { grab } = require("./mkteammatch.js");
const ROOT = path.join(__dirname, "..");
const NAMES = ["trimToOdds", "CHANGE_FROM", "CHANGE_TO", "changeAllPlan", "changeOptions"];

function build(src) {
  return "\"use strict\";\n" +
    "/* GENERATED by scripts/mkslipedit.js from public/index.html - do not edit.\n" +
    "   Re-run that script after changing these edits in the page. */\n" +
    NAMES.map((n) => grab(src, n)).join("\n") +
    "\nmodule.exports = { trimToOdds, CHANGE_FROM, CHANGE_TO, changeAllPlan, changeOptions };\n";
}

if (require.main === module) {
  const src = fs.readFileSync(path.join(ROOT, "public", "index.html"), "utf8").replace(/\r\n/g, "\n");
  fs.writeFileSync(path.join(ROOT, "lib", "slipedit.js"), build(src));
  console.log("lib/slipedit.js written");
}
module.exports = { build };
