#!/usr/bin/env node
/* Writes lib/teammatch.js: the site's own team matcher, lifted verbatim out of
 * public/index.html, for server code that must pair games the way the page
 * does (the Telegram converter, lib/convert.js).
 *
 *   node scripts/mkteammatch.js
 *
 * Why a generated copy and not a runtime lift like scripts/b9match.js does:
 * in production the build splits index.html's script out into hashed files, so
 * a serverless function cannot read these functions from the page. The copy
 * is checked by test/teammatch.test.js, which fails the moment index.html's
 * matcher changes and this has not been re-run.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const NAMES = ["TEAM_ALIASES", "MATCH_WINDOW_MS", "normTeam", "normTeamRaw",
  "tokset", "teamMarkers", "sameVariant", "containsWords",
  "simTeams", "evStart", "sameSlot"];

function grab(src, name) {
  const re = new RegExp("(?:^|\\n)((?:var|const|function)\\s+" + name + "\\b)", "m");
  const m = re.exec(src);
  if (!m) throw new Error("not found in index.html: " + name);
  const i = m.index + m[0].indexOf(m[1]);
  const isFn = m[1].startsWith("function");
  let depth = 0, started = false;
  for (let k = i; k < src.length; k++) {
    const c = src[k];
    if (c === "{" || c === "[" || c === "(") { depth++; started = true; }
    else if (c === "}" || c === "]" || c === ")") {
      depth--;
      if (isFn && started && depth === 0 && c === "}") return src.slice(i, k + 1);
    } else if (c === ";" && depth === 0 && !isFn) return src.slice(i, k + 1);
  }
  throw new Error("could not find the end of " + name);
}

function build(src) {
  return "\"use strict\";\n" +
    "/* GENERATED by scripts/mkteammatch.js from public/index.html - do not edit.\n" +
    "   Re-run that script after changing the matcher in the page. */\n" +
    NAMES.map((n) => grab(src, n)).join("\n") +
    "\nvar NT_CACHE=Object.create(null),NT_SIZE=0;const NT_MAX=20000;\n" +
    "module.exports = { normTeam, simTeams, sameSlot, evStart, sameVariant };\n";
}

if (require.main === module) {
  const src = fs.readFileSync(path.join(ROOT, "public", "index.html"), "utf8");
  fs.writeFileSync(path.join(ROOT, "lib", "teammatch.js"), build(src));
  console.log("lib/teammatch.js written");
}
module.exports = { build };
